### ISSUE TITLE
first-half-comments

### ISSUE THREAD

**Issue by shababo** [charlesfrye/charlesfrye.github.io#5]
Sorry this isn't complete, haven't had as much time as I would have liked. I think the big picture points are most important. Mainly, I think the analogies between the needs/strategies of runtimes and LLMs could be clearer and more frontloaded.

https://github.com/charlesfrye/charlesfrye.github.io/blob/60cbe411b102bab34c14bf491b50f0439417fb35/_posts/2023-11-01-llm-cpu.markdown?plain=1#L11
- maybe keep it framed as a question? i'm still skeptical at this point, and saying "it is clear" makes me react poorly.

https://github.com/charlesfrye/charlesfrye.github.io/blob/60cbe411b102bab34c14bf491b50f0439417fb35/_posts/2023-11-01-llm-cpu.markdown?plain=1#L17
- awkward wording

https://github.com/charlesfrye/charlesfrye.github.io/blob/60cbe411b102bab34c14bf491b50f0439417fb35/_posts/2023-11-01-llm-cpu.markdown?plain=1#L38
- set up the problem of bottlenecks generally and in terms of both runtimes and LLMs so we can be prepared to take in this strategy
- or maybe even before this section setup the juxtaposition - the reader needs to grok the analogy/intersections between the two structures before they can appreciate the parallels in strategies/applications.
- also, i feel like this strategy is even more general than kernels/runtimes... like in liam's group we used this strategy all the time... i would often make more approximate models for online inference and design and then use slower inference with a more accurate or structured model offline. it's not 1:1, but like... not clear me to that this is something that is unique enough to demonstrate that LLMs are a building block of a computer system... this is more general to any computational system (i.e. a program that does an analysis vs a program that is a runtime).

https://github.com/charlesfrye/charlesfrye.github.io/blob/60cbe411b102bab34c14bf491b50f0439417fb35/_posts/2023-11-01-llm-cpu.markdown?plain=1#L142
- are they intermediates? i sort of see them as the representations/instantiations of the data that are actually used for computation. the registers are the things that go into and out of the CPU. they are the actual thing

https://github.com/charlesfrye/charlesfrye.github.io/blob/60cbe411b102bab34c14bf491b50f0439417fb35/_posts/2023-11-01-llm-cpu.markdown?plain=1#L151
- i don't know what a compiler pass means exactly so hard for me to take anything away from this. not sure if i'm a representative sample.

https://github.com/charlesfrye/charlesfrye.github.io/blob/60cbe411b102bab34c14bf491b50f0439417fb35/_posts/2023-11-01-llm-cpu.markdown?plain=1#L154
- this is good. this helps the reader prepare to connect ideas. more of this.

..To be continued.

**Comment by charlesfrye** [comment]
> are they intermediates? i sort of see them as the representations/instantiations of the data that are actually used for computation. the registers are the things that go into and out of the CPU. they are the actual thing

I think of them as intermediates because 1) they "cannot be observed", aside from at the assembler level or below, and 2) because they literally cannot be observed across processes/threads, the output of a program is "always" a change to the state of memory, not to the registers

**Comment by charlesfrye** [comment]
> i don't know what a compiler pass means exactly so hard for me to take anything away from this. not sure if i'm a representative sample.

Maybe "e.g. by a compiler optimizing the program" would be clearer?

**Comment by charlesfrye** [comment]
> maybe keep it framed as a question? i'm still skeptical at this point, and saying "it is clear" makes me react poorly.

Reordering to "Like relational data stores or OS kernels, LLMs are {foundational}". On re-read, I agree with your assessment that "It is clear" is too strident.

**Comment by charlesfrye** [comment]
> > are they intermediates? i sort of see them as the representations/instantiations of the data that are actually used for computation. the registers are the things that go into and out of the CPU. they are the actual thing
> 
> I think of them as intermediates because 1) they "cannot be observed", aside from at the assembler level or below, and 2) because they literally cannot be observed across processes/threads, the output of a program is "always" a change to the state of memory, not to the registers

"Programs generally achieve their effects on the world by writing information to memory visible to other processes or hardware -- RAM, disk, the network, etc. Registers store small amounts of intermediate data during the computation of this information."
