### ISSUE TITLE
more-shababo-comments

### ISSUE THREAD

**Issue by shababo** [charlesfrye/charlesfrye.github.io#6]
https://github.com/charlesfrye/charlesfrye.github.io/blob/60cbe411b102bab34c14bf491b50f0439417fb35/_posts/2023-11-01-llm-cpu.markdown?plain=1#L224
- isn't it true that memory only became an issue when chrome was released and used one process per tab? this is relevant i think.

https://github.com/charlesfrye/charlesfrye.github.io/blob/60cbe411b102bab34c14bf491b50f0439417fb35/_posts/2023-11-01-llm-cpu.markdown?plain=1#L222
- this opening is great. clearly explains what part of a kerne we are going to apply to an LLM!

https://github.com/charlesfrye/charlesfrye.github.io/blob/60cbe411b102bab34c14bf491b50f0439417fb35/_posts/2023-11-01-llm-cpu.markdown?plain=1#L251
- i'm immediately curious how these "intermediate" values relate to the register stuff

https://github.com/charlesfrye/charlesfrye.github.io/blob/60cbe411b102bab34c14bf491b50f0439417fb35/_posts/2023-11-01-llm-cpu.markdown?plain=1#L253
- a reference would be good here

https://github.com/charlesfrye/charlesfrye.github.io/blob/60cbe411b102bab34c14bf491b50f0439417fb35/_posts/2023-11-01-llm-cpu.markdown?plain=1#L290
- is it crucial here that this LLM is handling two requests at once... would be nice to know how this type of system is setup since that informs what's at issue here - like if these were two LLMs on different machines, they would not have a problem. In this case, it's one LLM process on the CPU or multiple? Curious to get a little bit of context on that to help me see the parallel to the runtime case.

https://github.com/charlesfrye/charlesfrye.github.io/blob/60cbe411b102bab34c14bf491b50f0439417fb35/_posts/2023-11-01-llm-cpu.markdown?plain=1#L301
-  `0x0BF4eva`!!!!!

https://github.com/charlesfrye/charlesfrye.github.io/blob/60cbe411b102bab34c14bf491b50f0439417fb35/_posts/2023-11-01-llm-cpu.markdown?plain=1#L313
- oh, you had this planned...

https://github.com/charlesfrye/charlesfrye.github.io/blob/60cbe411b102bab34c14bf491b50f0439417fb35/_posts/2023-11-01-llm-cpu.markdown?plain=1#L357C1-L357C13
- "analogically".... maybe it's a word, i'm not even gonna look it up. sounds like not a word.

https://github.com/charlesfrye/charlesfrye.github.io/blob/60cbe411b102bab34c14bf491b50f0439417fb35/_posts/2023-11-01-llm-cpu.markdown?plain=1#L355
- for me, this section is by far the one that actually talks about using an LLM like a runtime... somehow this one needs to either to go first, or probably last is best... but it could be used as an opportunity to anchor the whole thing?

https://github.com/charlesfrye/charlesfrye.github.io/blob/60cbe411b102bab34c14bf491b50f0439417fb35/_posts/2023-11-01-llm-cpu.markdown?plain=1#L374
- not surprising that the most agent like situation is the most runtime like... though i'm still hot on the trail of understanding why i'm not surprised

https://github.com/charlesfrye/charlesfrye.github.io/blob/60cbe411b102bab34c14bf491b50f0439417fb35/_posts/2023-11-01-llm-cpu.markdown?plain=1#L378
- also reminds me of caching or speculative processing! maybe more than the previous example(s)

https://github.com/charlesfrye/charlesfrye.github.io/blob/60cbe411b102bab34c14bf491b50f0439417fb35/_posts/2023-11-01-llm-cpu.markdown?plain=1#L393
- boom. this is key. again - this section feels so much more relevant... if you are going to compare and contrast... this section is compare, the others more contrast almost..?

>Interruptibility and event-driven-ness are key features of biological agents as well.
To quote Copilot's suggested completion of this paragraph:
"If you poke a cat, it will stop what it's doing and respond to the poke."
- :)

>The event of that suggestion's appearance while drafting this post
interrupted my drafting task, triggering me to reflect on it
and then resume my drafting task with a new idea for what to say next.
- I like this but worded awkwardly atm

>It is clear that if LLMs are to become the cognitive kernels
of agents in any way worthy of the name,
they will need a similar architecture.
- weeeeeeee
- i think move this section to the top. give us the goods up front... i'm worried people on the fringes of this convo will not have a hook soon enough. for me, as you clearly know, this part is the hook.

> cognitive kernels
- :heart:

> Whether your background is in systems or ML,
you'll find a lot of value in thinking
"across the divide" and  your knowledge to the other field.
- some grammar issue or missing words here?

**Comment by charlesfrye** [comment]
> isn't it true that memory only became an issue when chrome was released and used one process per tab? this is relevant i think.

that's what I meant by "Browser Nation". replacing w "Chrome Nation" plus a link to a meme about RAM-hungriness

**Comment by charlesfrye** [comment]
> a reference would be good here

ACK

**Comment by charlesfrye** [comment]
> s it crucial here that this LLM is handling two requests at once... would be nice to know how this type of system is setup since that informs what's at issue here - like if these were two LLMs on different machines, they would not have a problem. In this case, it's one LLM process on the CPU or multiple? Curious to get a little bit of context on that to help me see the parallel to the runtime case.

one LLM handling multiple requests - the analogy would be that virtual memory is necessary for protection only when you have more than one process, e.g. the kernel and literally anything else

**Comment by charlesfrye** [comment]
> 0x0BF4eva!!!!!

`hexParseError: unknown symbol "v"`

**Comment by charlesfrye** [comment]
> "analogically".... maybe it's a word, i'm not even gonna look it up. sounds like not a word.

it's [hella cromulent](https://en.wiktionary.org/wiki/analogically)

**Comment by charlesfrye** [comment]
> for me, this section is by far the one that actually talks about using an LLM like a runtime... somehow this one needs to either to go first, or probably last is best... but it could be used as an opportunity to anchor the whole thing?

Yes, if the goal was to talk about using LLMs as runtimes, it'd be important to emphasize this section more and reorganize around it.

But my goal is just to get folks excited about this research intersection -- to get MLRs thinking about async runtimes and to show hardcore Rustaceans how MLRs react to their perspective.

That goal was unclear (in the text and even sometimes in my head) so I've made some adjustments to clarify it.

**Comment by charlesfrye** [comment]
> I like this but worded awkwardly atm

The wording was meant to mimic the way we talk about async/interrupted code as much as possible -- funny that it makes something so intuitive feel foreign. Rewording.
